<?php
$fullName = trim($student['last_name'] . ' ' . $student['first_name'] . ' ' . ($student['middle_name'] ?? ''));
$age = null;
if (!empty($student['birth_date'])) { $birth = new DateTimeImmutable($student['birth_date']); $age = $birth->diff(new DateTimeImmutable('today'))->y; }
$trainingLabels = \App\Models\StudentProfile::TRAINING_STATUSES;
$gearboxLabels = \App\Models\StudentProfile::GEARBOXES;
$genderLabels = \App\Models\StudentProfile::GENDERS;
$customerLabels = \App\Models\StudentProfile::CUSTOMER_TYPES;
$canManage = $currentUser->canManageEducation();
$isDismissed = $student['training_status'] === 'dismissed';
?>
<section class="student-hero panel reveal">
    <div class="student-photo"><?php if ($student['photo_path']): ?><img src="<?= e(url('/education/students/' . $student['id'] . '/photo')) ?>" alt="Фото <?= e($fullName) ?>"><?php else: ?><span><?= e(initials($student['first_name'], $student['last_name'])) ?></span><?php endif; ?></div>
    <div class="student-hero__copy"><p class="page-eyebrow">Карточка курсанта · №<?= (int) $student['id'] ?></p><h2><?= e($fullName) ?></h2><div class="student-hero__chips"><span class="status-pill status-pill--<?= $student['training_status'] === 'active' ? 'active' : 'blocked' ?>"><i></i><?= e($trainingLabels[$student['training_status']] ?? $student['training_status']) ?></span><span><?= $class ? 'Класс ' . e($class['group_number']) : 'Без класса' ?></span><span><?= $student['driving_allowed'] ? 'Допущен к вождению' : 'Нет допуска к вождению' ?></span></div></div>
    <div class="student-hero__balance"><small>Задолженность</small><strong><?= e(number_format((float) $totals['debt_total'], 2, ',', ' ')) ?> ₽</strong><span>Оплачено <?= e(number_format((float) $totals['paid_total'], 2, ',', ' ')) ?> ₽</span></div>
</section>

<nav class="anchor-tabs student-tabs" data-student-tabs role="tablist" aria-label="Разделы карточки курсанта"><a class="is-active" href="#main" data-student-tab="main" role="tab" aria-controls="main" aria-selected="true">Главное</a><a href="#personal" data-student-tab="personal" role="tab" aria-controls="personal" aria-selected="false" tabindex="-1">Личное</a><a href="#contracts" data-student-tab="contracts" role="tab" aria-controls="contracts" aria-selected="false" tabindex="-1">Договоры</a><a href="#payments" data-student-tab="payments" role="tab" aria-controls="payments" aria-selected="false" tabindex="-1">Услуги и оплаты</a><a href="#learning" data-student-tab="learning" role="tab" aria-controls="learning" aria-selected="false" tabindex="-1">Обучение</a><a href="#files" data-student-tab="files" role="tab" aria-controls="files" aria-selected="false" tabindex="-1">Файлы</a><a href="#events" data-student-tab="events" role="tab" aria-controls="events" aria-selected="false" tabindex="-1">События</a></nav>

<?php if ($canManage): ?>
<section class="panel reveal student-actions-panel student-tab-panel" data-student-tab-panel="main">
    <div><p class="page-eyebrow">Действия</p><h3>Действия с курсантом</h3></div>
    <div class="student-actions">
        <form method="post" action="<?= e(url('/education/students/' . $student['id'] . '/action')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="<?= $student['driving_allowed'] ? 'deny_driving' : 'allow_driving' ?>"><button class="button button--secondary" type="submit"><?= icon($student['driving_allowed'] ? 'lock' : 'unlock', 17) ?> <?= $student['driving_allowed'] ? 'Отменить допуск' : 'Допустить к вождению' ?></button></form>
        <form id="studentStatusActionForm" method="post" action="<?= e(url('/education/students/' . $student['id'] . '/action')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="<?= $isDismissed ? 'restore' : 'dismiss' ?>"><button class="button button--secondary <?= $isDismissed ? '' : 'button--danger-soft' ?>" type="button" data-dialog-open="studentStatusConfirmModal" aria-haspopup="dialog" aria-controls="studentStatusConfirmModal"><?= $isDismissed ? 'Восстановить' : 'Отчислить' ?></button></form>
        <form class="student-transfer" method="post" action="<?= e(url('/education/students/' . $student['id'] . '/transfer')) ?>"><?= csrf_field() ?><select name="class_id" required><option value="">Перевести в класс</option><?php foreach ($classes as $availableClass): ?><option value="<?= (int) $availableClass['id'] ?>" <?= $class && (int) $class['id'] === (int) $availableClass['id'] ? 'disabled' : '' ?>><?= e($availableClass['group_number'] . ' · ' . $availableClass['name']) ?></option><?php endforeach; ?></select><?= date_picker('joined_on', date('Y-m-d'), false, false, 'Дата перевода') ?><button class="button button--secondary" type="submit">Перевести</button></form>
        <a class="button button--secondary" href="<?= e(url('/education/students/' . $student['id'] . '/contract/print')) ?>" target="_blank"><?= icon('file', 17) ?> Сформировать документ</a>
    </div>
</section>

<dialog class="modal modal--compact" id="studentStatusConfirmModal" aria-labelledby="studentStatusConfirmTitle" aria-describedby="studentStatusConfirmText">
    <div class="modal__surface">
        <div class="confirm-icon <?= $isDismissed ? '' : 'is-danger' ?>"><?= icon($isDismissed ? 'unlock' : 'lock', 26) ?></div>
        <div class="modal__body modal__body--center">
            <h2 id="studentStatusConfirmTitle"><?= $isDismissed ? 'Восстановить курсанта?' : 'Отчислить курсанта?' ?></h2>
            <p id="studentStatusConfirmText"><?php if ($isDismissed): ?>Статус курсанта снова станет активным. При необходимости добавьте его обратно в учебный класс отдельно.<?php else: ?>Курсант будет отчислен, допуск к вождению отменён, а активное зачисление в класс завершено.<?php endif; ?></p>
        </div>
        <div class="modal__footer modal__footer--center">
            <button class="button button--ghost" type="button" data-dialog-close>Отмена</button>
            <button class="button <?= $isDismissed ? 'button--primary' : 'button--danger' ?>" type="submit" form="studentStatusActionForm"><?= $isDismissed ? 'Да, восстановить' : 'Да, отчислить' ?></button>
        </div>
    </div>
</dialog>
<?php endif; ?>

<section class="student-layout student-tab-panel" id="main" data-student-tab-panel="main personal">
    <article class="panel reveal student-section">
        <div class="panel__header" data-student-profile-view="main"><div><p class="page-eyebrow page-eyebrow--icon"><?= icon('user', 15) ?> Главное</p><h3>Основные данные</h3></div></div>
        <div class="panel__header" id="personal" data-student-profile-view="personal" hidden><div><p class="page-eyebrow page-eyebrow--icon"><?= icon('lock', 15) ?> Личное</p><h3>Личные данные и заказчик</h3></div></div>
        <?php if ($canManage): ?><form method="post" enctype="multipart/form-data" action="<?= e(url('/education/students/' . $student['id'] . '/profile')) ?>" class="stage-form" data-student-profile-form><?= csrf_field() ?><input type="hidden" name="active_tab" value="main" data-student-active-tab><div class="form-grid" data-student-profile-view="main">
            <label class="field"><span class="field__label">Окончание обучения</span><?= date_picker('training_end_on', $student['training_end_on'], false, false, 'Окончание обучения') ?></label>
            <label class="field"><span class="field__label">Коробка передач</span><span class="field__control"><select name="gearbox"><option value="">Не указана</option><?php foreach ($gearboxLabels as $key => $label): ?><option value="<?= e($key) ?>" <?= $student['gearbox'] === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></span></label>
            <label class="field"><span class="field__label">Пол</span><span class="field__control"><select name="gender"><option value="">Не указан</option><?php foreach ($genderLabels as $key => $label): ?><option value="<?= e($key) ?>" <?= $student['gender'] === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></span></label>
            <label class="field"><span class="field__label">Дата рождения</span><?= date_picker('birth_date', $student['birth_date'], false, false, 'Дата рождения') ?></label>
            <label class="field"><span class="field__label">Гражданство</span><span class="field__control"><input name="citizenship" value="<?= e($student['citizenship']) ?>"></span></label>
            <label class="field"><span class="field__label">Регистрационный номер</span><span class="field__control"><input name="registration_number" value="<?= e($student['registration_number']) ?>"></span></label>
            <label class="field form-grid__wide"><span class="field__label">Место рождения</span><span class="field__control"><input name="birth_place" value="<?= e($student['birth_place']) ?>"></span></label>
            <label class="field form-grid__wide"><span class="field__label">Фото</span><span class="file-upload"><input class="sr-only" type="file" name="photo" accept="image/jpeg,image/png,image/webp" data-file-input><span class="file-upload__icon"><?= icon('upload', 21) ?></span><span class="file-upload__copy"><strong>Выберите новое фото</strong><small data-file-summary>JPG, PNG или WEBP · до 5 МБ</small></span><span class="file-upload__action">Выбрать</span></span></label>
            <label class="field form-grid__wide"><span class="field__label">Примечания</span><span class="field__control"><textarea name="notes" rows="3"><?= e($student['notes']) ?></textarea></span></label>
        </div><div class="student-profile-split" data-student-profile-view="personal" hidden><div><h4>Личные данные</h4><div class="form-grid"><label class="field form-grid__wide"><span class="field__label">Адрес постоянной регистрации</span><span class="field__control"><input name="permanent_address" value="<?= e($student['permanent_address']) ?>"></span></label><label class="field form-grid__wide"><span class="field__label">Адрес временной регистрации</span><span class="field__control"><input name="temporary_address" value="<?= e($student['temporary_address']) ?>"></span></label><label class="field"><span class="field__label">СНИЛС</span><span class="field__control"><input name="snils" value="<?= e($student['snils']) ?>"></span></label></div></div><div><h4>Заказчик</h4><div class="form-grid"><label class="field"><span class="field__label">Тип заказчика</span><span class="field__control"><select name="customer_type"><?php foreach ($customerLabels as $key => $label): ?><option value="<?= e($key) ?>" <?= $student['customer_type'] === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></span></label><label class="field"><span class="field__label">ФИО или организация</span><span class="field__control"><input name="customer_name" value="<?= e($student['customer_name']) ?>"></span></label><label class="field form-grid__wide"><span class="field__label">Реквизиты заказчика</span><span class="field__control"><textarea name="customer_details" rows="3"><?= e($student['customer_details']) ?></textarea></span></label></div></div></div><div class="stage-form__actions"><button class="button button--primary" type="submit">Сохранить карточку</button></div></form>
        <?php else: ?><dl class="profile-readonly" data-student-profile-view="main"><div><dt>Дата рождения</dt><dd><?= e($student['birth_date'] ? format_date($student['birth_date'], 'd.m.Y') . ($age !== null ? ' · ' . $age . ' лет' : '') : '—') ?></dd></div><div><dt>Телефон</dt><dd><?= e($student['phone'] ?: '—') ?></dd></div><div><dt>Email</dt><dd><?= e($student['email'] ?: '—') ?></dd></div><div><dt>Класс</dt><dd><?= e($class['group_number'] ?? 'Без класса') ?></dd></div><div><dt>Преподаватель</dt><dd><?= e($class['teacher_name'] ?? '—') ?></dd></div><div><dt>Коробка передач</dt><dd><?= e($gearboxLabels[$student['gearbox']] ?? '—') ?></dd></div></dl><dl class="profile-readonly" data-student-profile-view="personal" hidden><div><dt>Постоянная регистрация</dt><dd><?= e($student['permanent_address'] ?: '—') ?></dd></div><div><dt>Временная регистрация</dt><dd><?= e($student['temporary_address'] ?: '—') ?></dd></div><div><dt>СНИЛС</dt><dd><?= e($student['snils'] ?: '—') ?></dd></div><div><dt>Тип заказчика</dt><dd><?= e($customerLabels[$student['customer_type']] ?? '—') ?></dd></div><div><dt>ФИО или организация</dt><dd><?= e($student['customer_name'] ?: '—') ?></dd></div><div><dt>Реквизиты</dt><dd><?= e($student['customer_details'] ?: '—') ?></dd></div></dl><?php endif; ?>
    </article>

    <aside class="student-sidebar" data-student-profile-view="main">
        <article class="panel"><p class="page-eyebrow">Контакты</p><h3><?= e($student['phone'] ?: 'Телефон не указан') ?></h3><p><?= e($student['email'] ?: 'Email не указан') ?></p><small>Логин: @<?= e($student['login']) ?></small></article>
        <article class="panel"><p class="page-eyebrow">Учебный класс</p><h3><?= e($class['group_number'] ?? 'Не назначен') ?></h3><p><?= e($class['name'] ?? 'Добавьте курсанта в класс') ?></p><?php if ($class): ?><a class="text-link" href="<?= e(url('/education/classes/' . $class['id'])) ?>">Открыть класс <?= icon('chevron-right', 15) ?></a><?php endif; ?></article>
    </aside>
</section>

<section class="panel reveal student-section student-tab-panel" id="documents" data-student-tab-panel="personal" hidden>
    <div class="panel__header"><div><p class="page-eyebrow">Документы</p><h3>Личные документы</h3></div></div>
    <div class="record-list compact-records"><?php foreach ($documents as $document): ?><article><div><strong><?= e($document['document_type']) ?></strong><small><?= e(trim(($document['series'] ?? '') . ' ' . ($document['number'] ?? '')) ?: 'Без номера') ?></small></div><span><?= $document['issued_on'] ? 'Выдан ' . e(format_date($document['issued_on'], 'd.m.Y')) : 'Дата не указана' ?></span><p><?= e($document['issued_by'] ?: 'Орган выдачи не указан') ?></p></article><?php endforeach; ?><?php if (!$documents): ?><div class="empty-inline">Документы ещё не добавлены.</div><?php endif; ?></div>
    <?php if ($canManage): ?><form class="inline-create-form" method="post" action="<?= e(url('/education/students/' . $student['id'] . '/documents')) ?>"><?= csrf_field() ?><input name="document_type" required placeholder="Вид документа"><input name="series" placeholder="Серия"><input name="number" placeholder="Номер"><?= date_picker('issued_on', '', false, false, 'Дата выдачи') ?><?= date_picker('expires_on', '', false, false, 'Срок действия') ?><input name="issued_by" placeholder="Кем выдан"><button class="button button--secondary" type="submit">Добавить</button></form><?php endif; ?>
</section>

<section class="panel reveal student-section student-tab-panel" id="contracts" data-student-tab-panel="contracts" hidden>
    <div class="panel__header"><div><p class="page-eyebrow">Договоры</p><h3>Договоры курсанта</h3></div><a class="text-link" href="<?= e(url('/education/students/' . $student['id'] . '/contract/print')) ?>" target="_blank">Печатная форма <?= icon('chevron-right', 15) ?></a></div>
    <div class="data-table-wrap"><table class="data-table stage-table"><thead><tr><th>Номер</th><th>Дата</th><th>Предмет</th><th>Сумма</th><th>Статус</th></tr></thead><tbody><?php foreach ($contracts as $contract): ?><tr><td><strong><?= e($contract['contract_number']) ?></strong></td><td><?= e(format_date($contract['signed_on'], 'd.m.Y')) ?></td><td><?= e($contract['subject']) ?></td><td><?= $contract['amount'] !== null ? e(number_format((float) $contract['amount'], 2, ',', ' ')) . ' ₽' : '—' ?></td><td><?= e(\App\Models\Contract::STATUSES[$contract['status']] ?? $contract['status']) ?></td></tr><?php endforeach; ?><?php if (!$contracts): ?><tr><td colspan="5"><div class="empty-inline">Договоры ещё не созданы.</div></td></tr><?php endif; ?></tbody></table></div>
    <?php if ($canManage): ?><details class="embedded-form"><summary>Создать договор</summary><form method="post" action="<?= e(url('/education/students/' . $student['id'] . '/contracts')) ?>" class="inline-create-form"><?= csrf_field() ?><input name="contract_number" placeholder="Номер (можно автоматически)"><input name="registration_number" placeholder="Регистрационный номер"><?= date_picker('signed_on', date('Y-m-d'), false, true, 'Дата заключения') ?><?= date_picker('starts_on', '', false, false, 'Начало действия') ?><?= date_picker('ends_on', '', false, false, 'Окончание действия') ?><input type="number" name="amount" min="0" step="0.01" placeholder="Сумма"><input type="hidden" name="status" value="active"><input type="hidden" name="direction" value="driving_school"><input type="hidden" name="subject" value="Обучение в автошколе"><input type="hidden" name="counterparty" value="<?= e($fullName) ?>"><button class="button button--primary" type="submit">Создать договор</button></form></details><?php endif; ?>
</section>

<section class="student-finance-grid student-tab-panel" id="payments" data-student-tab-panel="payments" hidden>
    <article class="panel reveal student-section">
        <div class="panel__header"><div><p class="page-eyebrow">Продажи</p><h3>Услуги</h3></div><strong><?= e(number_format((float) $totals['sold_total'], 2, ',', ' ')) ?> ₽</strong></div>
        <div class="finance-records"><?php foreach ($sales as $sale): ?><article><div><strong><?= e($sale['service_name']) ?></strong><small><?= e(format_date($sale['sold_on'], 'd.m.Y')) ?> · <?= e($sale['seller_name']) ?></small></div><div><b><?= e(number_format((float) $sale['amount'], 2, ',', ' ')) ?> ₽</b><small>Оплачено <?= e(number_format((float) $sale['paid_total'], 2, ',', ' ')) ?> ₽</small></div></article><?php endforeach; ?><?php if (!$sales): ?><div class="empty-inline">Продаж пока нет.</div><?php endif; ?></div>
        <?php if ($canManage): ?><form method="post" action="<?= e(url('/education/students/' . $student['id'] . '/sales')) ?>" class="stacked-form"><?= csrf_field() ?><label class="field"><span class="field__label">Услуга</span><span class="field__control"><select name="service_id" required><option value="">Выберите услугу</option><?php foreach ($services as $service): ?><option value="<?= (int) $service['id'] ?>" data-price="<?= e($service['price']) ?>"><?= e($service['name']) ?> · <?= e(number_format((float) $service['price'], 2, ',', ' ')) ?> ₽</option><?php endforeach; ?></select></span></label><div class="form-grid"><label class="field"><span class="field__label">Цена продажи</span><span class="field__control"><input type="number" name="amount" min="0.01" step="0.01" required></span></label><label class="field"><span class="field__label">Дата</span><?= date_picker('sold_on', date('Y-m-d'), false, true, 'Дата продажи') ?></label></div><label class="field"><span class="field__label">Примечание</span><span class="field__control"><input name="notes"></span></label><button class="button button--primary" type="submit">Продать услугу</button><?php if (!$services): ?><small class="form-warning">Сначала добавьте услугу в справочник.</small><?php endif; ?></form><?php endif; ?>
    </article>
    <article class="panel reveal student-section">
        <div class="panel__header"><div><p class="page-eyebrow">Оплаты</p><h3>Платежи и транши</h3></div><strong><?= e(number_format((float) $totals['paid_total'], 2, ',', ' ')) ?> ₽</strong></div>
        <div class="finance-records"><?php foreach ($payments as $payment): ?><article><div><strong><?= e(number_format((float) $payment['amount'], 2, ',', ' ')) ?> ₽</strong><small><?= e(format_date($payment['paid_on'])) ?> · <?= e($payment['kassa_name']) ?></small></div><div><b><?= e($payment['service_name'] ?: 'Без привязки к услуге') ?></b><small><?= e($payment['accepted_by_name']) ?></small></div></article><?php endforeach; ?><?php if (!$payments): ?><div class="empty-inline">Платежей пока нет.</div><?php endif; ?></div>
        <?php if ($currentUser->canAcceptPayments()): ?><form method="post" action="<?= e(url('/education/students/' . $student['id'] . '/payments')) ?>" class="stacked-form"><?= csrf_field() ?><label class="field"><span class="field__label">Продажа</span><span class="field__control"><select name="sale_id"><option value="">Без привязки</option><?php foreach ($sales as $sale): ?><option value="<?= (int) $sale['id'] ?>"><?= e($sale['service_name']) ?> · остаток <?= e(number_format(max(0, (float) $sale['amount'] - (float) $sale['paid_total']), 2, ',', ' ')) ?> ₽</option><?php endforeach; ?></select></span></label><div class="form-grid"><label class="field"><span class="field__label">Сумма транша</span><span class="field__control"><input type="number" name="amount" min="0.01" step="0.01" required></span></label><label class="field"><span class="field__label">Касса</span><span class="field__control"><select name="kassa_id" required><option value="">Выберите кассу</option><?php foreach ($kassas as $kassa): ?><option value="<?= (int) $kassa['id'] ?>"><?= e($kassa['name']) ?></option><?php endforeach; ?></select></span></label></div><label class="field"><span class="field__label">Дата и время</span><?= date_picker('paid_on', date('Y-m-d\TH:i'), true, true, 'Дата и время оплаты') ?></label><label class="field"><span class="field__label">Примечание</span><span class="field__control"><input name="notes"></span></label><button class="button button--primary" type="submit">Принять оплату</button><?php if (!$kassas): ?><small class="form-warning">Нет действующей кассы. Директор или заместитель должен создать её.</small><?php endif; ?></form><?php endif; ?>
    </article>
</section>

<section class="learning-grid student-tab-panel" id="learning" data-student-tab-panel="learning" hidden>
    <article class="panel reveal"><p class="page-eyebrow page-eyebrow--icon"><?= icon('book-open', 15) ?> Теория</p><h3>Освоенные темы</h3><p>Темы, материалы и результаты занятий будут появляться здесь после подключения раздела «Теория».</p><span class="empty-chip">Данных пока нет</span></article>
    <article class="panel reveal"><p class="page-eyebrow page-eyebrow--icon"><?= icon('car', 15) ?> Вождение</p><h3>История занятий</h3><p>Здесь будут начисленные, использованные и оставшиеся часы, а также история практических занятий.</p><span class="empty-chip">Данных пока нет</span></article>
    <article class="panel reveal"><p class="page-eyebrow page-eyebrow--icon"><?= icon('file', 15) ?> Документация</p><h3>Свидетельства</h3><p>Выданные свидетельства и другие итоговые документы будут связаны с карточкой курсанта.</p><span class="empty-chip">Данных пока нет</span></article>
    <article class="panel reveal"><p class="page-eyebrow page-eyebrow--icon"><?= icon('check-square', 15) ?> Точки контроля</p><h3>Зачёты и экзамены</h3><p>Статистика тестов и результаты контрольных точек появятся после реализации тестирования.</p><span class="empty-chip">Данных пока нет</span></article>
</section>

<section class="panel reveal student-section student-tab-panel" id="files" data-student-tab-panel="files" hidden>
    <div class="panel__header"><div><p class="page-eyebrow page-eyebrow--icon"><?= icon('paperclip', 15) ?> Файлы</p><h3>Файлы курсанта</h3></div></div>
    <div class="file-list"><?php foreach ($files as $file): ?><a href="<?= e(url('/education/student-files/' . $file['id'])) ?>"><span><?= icon('paperclip', 18) ?></span><span><strong><?= e($file['original_name']) ?></strong><small><?= e(format_bytes((int) $file['size_bytes'])) ?> · <?= e(format_date($file['created_at'])) ?></small></span><?= icon('download', 17) ?></a><?php endforeach; ?><?php if (!$files): ?><div class="empty-inline">Файлы ещё не загружены.</div><?php endif; ?></div>
    <?php if ($canManage): ?><form method="post" enctype="multipart/form-data" action="<?= e(url('/education/students/' . $student['id'] . '/files')) ?>" class="student-file-upload"><?= csrf_field() ?><label class="file-upload"><input class="sr-only" type="file" name="file" required data-file-input><span class="file-upload__icon"><?= icon('paperclip', 21) ?></span><span class="file-upload__copy"><strong>Выберите файл курсанта</strong><small data-file-summary>PDF, изображение или документ · до 20 МБ</small></span><span class="file-upload__action">Выбрать</span></label><button class="button button--secondary" type="submit"><?= icon('upload', 17) ?> Загрузить файл</button></form><?php endif; ?>
</section>

<section class="student-history-grid student-tab-panel" id="events" data-student-tab-panel="events" hidden>
    <article class="panel reveal"><div class="panel__header"><div><p class="page-eyebrow">История обучения</p><h3>Перемещения по классам</h3></div></div><div class="timeline-list"><?php foreach ($history as $item): ?><div class="timeline-item"><span class="timeline-item__marker"><?= icon('users', 16) ?></span><div class="timeline-item__body"><strong><?= e($item['group_number'] . ' · ' . $item['class_name']) ?></strong><p><?= e(format_date($item['joined_on'], 'd.m.Y')) ?> — <?= $item['left_on'] ? e(format_date($item['left_on'], 'd.m.Y')) : 'по настоящее время' ?></p></div></div><?php endforeach; ?><?php if (!$history): ?><div class="empty-inline">Истории зачисления пока нет.</div><?php endif; ?></div></article>
    <article class="panel reveal"><div class="panel__header"><div><p class="page-eyebrow page-eyebrow--icon"><?= icon('activity', 15) ?> Лента событий</p><h3>Изменения карточки</h3></div></div><div class="timeline-list"><?php foreach ($events as $event): ?><div class="timeline-item"><span class="timeline-item__marker"><?= icon('activity', 16) ?></span><div class="timeline-item__body"><strong><?= e($event['action_name']) ?></strong><p><?= e($event['actor_name']) ?> · <?= e(format_date($event['created_at'])) ?></p></div></div><?php endforeach; ?><?php if (!$events): ?><div class="empty-inline">Событий пока нет.</div><?php endif; ?></div></article>
</section>
