<?php
$monthDate = $calendar['start'];
$previousMonth = $monthDate->modify('-1 month')->format('Y-m');
$nextMonth = $monthDate->modify('+1 month')->format('Y-m');
$monthNames = [1=>'Январь',2=>'Февраль',3=>'Март',4=>'Апрель',5=>'Май',6=>'Июнь',7=>'Июль',8=>'Август',9=>'Сентябрь',10=>'Октябрь',11=>'Ноябрь',12=>'Декабрь'];
$cursor = $calendar['grid_start'];
$gridEnd = $calendar['grid_end'];
?>
<section class="section-heading reveal"><div><h2>Календарь занятий</h2><p><?php if ($currentUser->role === 'student'): ?>Ваше расписание учебного класса.<?php elseif ($currentUser->role === 'teacher'): ?>Занятия назначенных вам классов.<?php elseif ($currentUser->role === 'instructor'): ?>Ваш персональный календарь; практические слоты появятся на этапе «Вождение».<?php else: ?>Общий календарь с классами, преподавателями и числом курсантов.<?php endif; ?></p></div><?php if ($currentUser->canManageEducation()): ?><a class="button button--secondary" href="<?= e(url('/education/holidays')) ?>"><?= icon('settings', 18) ?> Выходные дни</a><?php endif; ?></section>

<section class="panel calendar-panel reveal">
    <div class="calendar-toolbar"><div class="calendar-toolbar__nav"><a class="icon-button" href="<?= e(url('/calendar?month=' . $previousMonth)) ?>" aria-label="Предыдущий месяц"><?= icon('chevron-left', 18) ?></a><h3><?= e($monthNames[(int) $monthDate->format('n')] . ' ' . $monthDate->format('Y')) ?></h3><a class="icon-button" href="<?= e(url('/calendar?month=' . $nextMonth)) ?>" aria-label="Следующий месяц"><?= icon('chevron-right', 18) ?></a></div><?php if ($currentUser->canManageEducation()): ?><form method="get" action="<?= e(url('/calendar')) ?>" class="calendar-filters"><input type="hidden" name="month" value="<?= e($month) ?>"><select name="class_id" onchange="this.form.submit()"><option value="">Все классы</option><?php foreach ($classes as $class): ?><option value="<?= (int) $class['id'] ?>" <?= (int) $filters['class_id'] === (int) $class['id'] ? 'selected' : '' ?>><?= e($class['group_number']) ?></option><?php endforeach; ?></select><select name="teacher_id" onchange="this.form.submit()"><option value="">Все преподаватели</option><?php foreach ($teachers as $teacher): ?><option value="<?= $teacher->id ?>" <?= (int) $filters['teacher_id'] === $teacher->id ? 'selected' : '' ?>><?= e($teacher->fullName()) ?></option><?php endforeach; ?></select></form><?php endif; ?></div>
    <div class="month-calendar"><div class="month-calendar__weekdays"><?php foreach (['Пн','Вт','Ср','Чт','Пт','Сб','Вс'] as $day): ?><span><?= $day ?></span><?php endforeach; ?></div><div class="month-calendar__grid">
        <?php while ($cursor <= $gridEnd): $dateKey = $cursor->format('Y-m-d'); $outside = $cursor->format('Y-m') !== $month; $holiday = $calendar['holidays'][$dateKey] ?? null; ?>
            <article class="calendar-day <?= $outside ? 'is-outside' : '' ?> <?= $holiday ? 'is-holiday' : '' ?>"><div class="calendar-day__top"><strong><?= e($cursor->format('j')) ?></strong><?php if ($holiday): ?><span title="<?= e($holiday['name']) ?>">Выходной</span><?php endif; ?></div><div class="calendar-day__events"><?php foreach ($calendar['events'][$dateKey] ?? [] as $event): ?><a class="calendar-event" href="<?= e(url($currentUser->isStudent() ? '/education/students/' . $currentUser->id : '/education/classes/' . $event['class_id'] . '#schedule')) ?>"><time><?= e(format_date($event['starts_at'], 'H:i')) ?></time><strong><?= e($event['group_number']) ?></strong><span><?= e($event['class_name']) ?></span><?php if ($currentUser->canManageEducation()): ?><small><?= e($event['teacher_name']) ?> · <?= (int) $event['student_count'] ?> курс.</small><?php elseif ($currentUser->role === 'student'): ?><small><?= e($event['classroom'] ?: 'Кабинет не указан') ?></small><?php endif; ?></a><?php endforeach; ?></div></article>
        <?php $cursor = $cursor->modify('+1 day'); endwhile; ?>
    </div></div>
</section>
